// Actions de carrito
export const CHANGE_CARRITO_PROPS = "CHANGE_CARRITO_PROPS";
export const AGREGAR_UNO_AL_CARRITO = "AGREGAR_UNO_AL_CARRITO";
export const ELIMINAR_DEL_CARRITO = "ELIMINAR_DEL_CARRITO"